name: Docker

on:
  schedule:
    - cron: '26 17 * * *' # Hora configurada del segundo YAML
  push:
    # Solo se activa en push de tags sem치nticos
    tags: [ 'v*.*.*' ]
  # pull_request eliminado como en la segunda versi칩n

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image (frontend - production)
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .                      
          file: ./Dockerfile              
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: production              #  Tag para que coja el Dockerfile de producci칩n
          # cache-from y cache-to para mejorar la velocidad de construcci칩n
          cache-from: type=gha
          cache-to: type=gha,mode=max



      - name: Notificar despliegue a Teams
        env:
          WEBHOOK_URL: >-
            https://prod-50.westeurope.logic.azure.com:443/workflows/db21453690d446649c9933479139312d/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=cAY6WgDEeyrIMv_XbG-2kkdj8lon8B5-6GR1v3ZWqo4
          REPO: ${{ github.repository }}
          ACTOR: ${{ github.actor }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          FECHA=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          TAG=$(echo "$TAGS" | cut -d',' -f1)

          cat > payload.json <<EOF
          {
            "repo": "$REPO",
            "tag": "$TAG",
            "digest": "$DIGEST",
            "actor": "$ACTOR",
            "fecha": "$FECHA"
          }
          EOF

              echo "游닋 Enviando payload a Teams..."
              cat payload.json

              curl -X POST "$WEBHOOK_URL" \
                -H "Content-Type: application/json" \
                --data @payload.json



